spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:scraper}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USERNAME:}
  mail:
    host: smtp.gmail.com
    port: 587
    username: chihab.hajji@esprit.tn
    password: ${GMAIL_PW}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true